#!/bin/sh

#Main script code
Main() {
	#sudo cp -Rf /I-Doser\ Free.app /Applications/I-Doser\ Free/
	#sudo rm -rf /I-Doser\ Free.app

	sudo cp -Rf "/Applications/I-Doser Free/I-Doser Free.app/Contents/Resources/Data/Dose Files" ~/Documents/
	sudo rm -Rf ~/Documents/Dose\ Files/MP3\ Backgrounds
	sudo rm -Rf ~/Documents/Dose\ Files/Alert+.drg
	sudo rm -Rf ~/Documents/Dose\ Files/F_Roast.drg
	sudo rm -Rf ~/Documents/Dose\ Files/Beta.drg
	
	sudo chmod -R 777 ~/Documents/Dose\ Files
	sudo chmod -R 777 "/Applications/I-Doser Free"
	sudo chmod -R 777 ~/Library/Preferences/com.apple.dock.plist
	
	return 0
}



# Open Web-browser
OpenURLWithDefaultBrowser() {
	
	URL="http://www.idosersoftware.com"

	echo `defaults read ~/Library/Preferences/com.apple.LaunchServices`

	HAVE_HTTP=`defaults read ~/Library/Preferences/com.apple.LaunchServices | grep http`
	if [ "$HAVE_HTTP" = "" ]
	then
		echo "Don't Have Default Browser"
		open "$URL"
		return 0
	fi


	echo "Have Default Browser"


	FOUND_BROWSER=""
	COUNTER=0
	while [ $COUNTER -lt 100 ]; do
		URL_SCHEME=`sudo /usr/libexec/PlistBuddy -c "Print :LSHandlers:$COUNTER:LSHandlerURLScheme" ~/Library/Preferences/com.apple.LaunchServices.plist`
		
		echo "Url sheme: $URL_SCHEME"
		
		if [ "$URL_SCHEME" = "http" ]
		then
			echo "Found Browser For HTTP Sheme: $COUNTER"
		    FOUND_BROWSER="1"
			break
		fi
		
		if [ "$URL_SCHEME" = "https" ]
		then
			echo "Found Browser For HTTPS Sheme: $COUNTER"
			FOUND_BROWSER="1"
			break
		fi
	
		
	    (( COUNTER++ ))
	done


	if [ "$FOUND_BROWSER" = "1" ]
	then
		BROWSER=`sudo /usr/libexec/PlistBuddy -c "Print :LSHandlers:$COUNTER:LSHandlerRoleAll" ~/Library/Preferences/com.apple.LaunchServices.plist`
	
		echo "Default Browser is: $BROWSER"
	
		open -b "$BROWSER" "$URL"
		
		return 0
	fi
	
	echo "!!! 0_____________o Cant find Default Browser For HTTP/HTTPS Sheme: $COUNTER"
	
	open "$URL"
	
	return 0
}




#Add icon to the Dock
AddDockIcon() {
	COUNTER=0
	while [ $COUNTER -lt 100 ]; do
		BUNDLE_ID=`sudo /usr/libexec/PlistBuddy -c "Print :persistent-apps:$COUNTER:tile-data:bundle-identifier" ~/Library/Preferences/com.apple.dock.plist`
	
		echo "Bundle ID: $BUNDLE_ID"

		if [ "$BUNDLE_ID" = "com.alankong.IDoserFree" ]
		then
			echo "IDoserFree already exist in Dock"
			break
		fi

		if [ "$BUNDLE_ID" = "" ]
		then
			echo "Found Free space at the Dock: $COUNTER"
			sudo /usr/libexec/PlistBuddy -c "Add :persistent-apps:$COUNTER:tile-data:file-data:_CFURLString string '/Applications/I-Doser Free/I-Doser Free.app/'" ~/Library/Preferences/com.apple.dock.plist
			sudo /usr/libexec/PlistBuddy -c "Add :persistent-apps:$COUNTER:tile-data:file-data:_CFURLStringType integer 0" ~/Library/Preferences/com.apple.dock.plist

			defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/I-Doser Free/I-Doser Free.app/</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
			
			break
		fi
	
	    (( COUNTER++ ))
	done
	
	osascript -e 'tell application "Finder" to make new alias file at desktop to POSIX file "/Applications/I-Doser Free/I-Doser Free.app"'

	killall "Dock"

	echo "Dock Test"
}







Main

OpenURLWithDefaultBrowser

AddDockIcon



exit 0
