#!/bin/sh
sudo rm -rf ~/Desktop/I-Doser\ Free
sudo rm -rf ~/Desktop/I-Doser\ Premium
sudo rm -rf /Applications/I-Doser\ Premium
sudo rm -rf /Applications/I-Doser\ Free
#mkdir -m 0777 /Applications/I-Doser\ Free

HAVE_PREMIUM_VER_INSTALLED=`defaults read ~/Library/Preferences/com.apple.dock | grep com.alankong.IDoserPremium`
if [ "$HAVE_PREMIUM_VER_INSTALLED" != "" ]
then
	echo "Have Free dock icon"
	
	COUNTER=0
	while [ $COUNTER -lt 100 ]; do
		BUNDLE_ID=`sudo /usr/libexec/PlistBuddy -c "Print :persistent-apps:$COUNTER:tile-data:bundle-identifier" ~/Library/Preferences/com.apple.dock.plist`
	
		echo "Bundle ID: $BUNDLE_ID"
	
		if [ "$BUNDLE_ID" = "com.alankong.IDoserPremium" ]
		then
			echo "Found Premium Version: $COUNTER"
			
			sudo /usr/libexec/PlistBuddy -c "Delete :persistent-apps:$COUNTER" ~/Library/Preferences/com.apple.dock.plist
			
			break
		fi
	
	    (( COUNTER++ ))
	done

fi

exit 0