version: '2.1'

services:
  postgresql:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432' # expose ports - HOST:CONTAINER
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresdatahack:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
